print("Program Menghitung Harga Jual Barang")
print("visit us @hobingoding.com")
print()
harga_beli = int(input("Input Harga Beli : "))
print("Opsi Perhitungan : ")
print("1. Untung")
print("2. Rugi")
opsi = int(input("Input Opsi Perhitungan : "))
persen = int(input("Input Persentase Untung-Rugi : "))
if(opsi == 1):
    harga_jual = harga_beli+(harga_beli*persen/100)
    print("Harga Jual jika untung sebesar %s persen adalah %s"%(persen, harga_jual))
else:
    harga_jual = harga_beli-(harga_beli*persen/100)
    print("Harga Jual jika rugi sebesar %s persen adalah %s"%(persen, harga_jual))
